[workspace]
members = [
    "lib/shared",
#    "archives/shared2",
    "micro/gateway",
#    "micro/cmaster",
    "micro/db_view",
    "micro/logic",
    "micro/play",
    "micro/tmp",

]
exclude =[
#    "micro/logic",
    "micro/cmaster",

]