[workspace]
members = [
    "lib/shared",
    "lib/shared2",
    "micro/gateway",
#    "micro/cmaster",
    "micro/db_view",
    "micro/logic",
    "micro/play",

]
exclude =[
#    "micro/logic"
    "micro/cmaster"
]