[workspace]
members = [
    "lib/shared",
#    "archives/shared2",
    "micro/gateway",
#    "micro/cmaster",
    "micro/db_view",
    "micro/logic",

    # Dev Playground
    "dev_play/play",
    "dev_play/tmp",

]
exclude =[
#    "micro/logic",
    "micro/cmaster",

]